# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CVAppCenter' do
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', '~> 1.12.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CVAppCenter

  

  platform :ios, '9.0'
  target 'CVAppCenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CVAppCenter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CVAppCenter-tvOS

  target 'CVAppCenter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
